### PR TITLE
Update otel libraries to v1.20.0

### PR DESCRIPTION
**Pull request by emcfarlane**
Dependency updates. Update for otel v1.20.0, connect v1.12.0 and go-cmp 0.6.

### CODE REVIEW

**Review by pkwarren — APPROVED** [review]

**Comment by pkwarren** [comment]
Looks like we'll need to bump to Go 1.20 to pick up the latest version:

```
Error: ../../../go/pkg/mod/go.opentelemetry.io/otel/sdk/metric@v1.20.0/meter.go:472:26: undefined: errors.Join
Error: ../../../go/pkg/mod/go.opentelemetry.io/otel/sdk/metric@v1.20.0/meter.go:516:26: undefined: errors.Join
note: module requires Go 1.20
```

**Comment by emcfarlane** [comment]
Reverted the changes just to connect and go-cmp. No changes needed for v1.20 so safe to close or merge the connect update.

**Comment by akshayjshah** [comment]
Do we need any of these changes? I don't like habitually bumping dependencies in libraries, because it _forces_ end-users to upgrade. If we need a feature from the new Connect or cmp releases, that's fine. Otherwise, why not leave end users more freedom?

**Comment by emcfarlane** [comment]
@akshayjshah yes totally not. I saw libraries required changes so was concerned if we needed any updates. All good though, closing!

**Pull request closed without merging**
