### PR TITLE
Align gRPC server status code to span status code

### PR DESCRIPTION
**Pull request by dragon3**
This pull request fixes https://github.com/connectrpc/otelconnect-go/issues/122

refs:
- https://github.com/open-telemetry/opentelemetry-specification/pull/3333
- https://github.com/open-telemetry/opentelemetry-go-contrib/pull/3685

### CODE REVIEW

**Comment by akshayjshah** [comment]
Thank you for the contribution, @dragon3! This repository - and the OpenTelemetry RPC semantic conventions - are in a strange state right now, because Google's gRPC projects are planning to _directly_ support OpenTelemetry, but they don't plan to follow the OTel RPC semantic conventions. (See grpc/proposal#380 for details.) If Google's gRPC implementations aren't following the proposed semantic conventions, there may not be much value in us following it either.

Before merging this PR, we'd like to discuss the best path forward a bit more among the maintainers, followed by a more open discussion on a GitHub issue. Let's keep this PR open until we make a decision.

**Comment by dragon3** [comment]
@akshayjshah 
Thank you for the reply.

I didn't know the situation and it's interesting 😅  I also find https://github.com/grpc/proposal/pull/389
I hope Google's gRPC implementation will follow the OTel semantic conventions for both metrics, and tracing ( also logging in the future )

Let me explain my motivation to create this PR.

I develop and maintain both gRPC and ConnectRPC services every day for my company. Of course, I use OpenTelemetry for both gRPC and ConnectRPC services observability. That's great but the difference in the span status code between them is a bit annoying.

For example, in gRPC `NOT_FOUND` span status is `Unset`, it's good to me to monitor the service's error rate and alerting. But in ConnectRPC the status is `Error`, it's not great to me because it's expected one and I don't want to count as error, then hard to monitor the service.

I'd like to unify the span status ( follow the current gRPC's status ), that's my motivation.

Anyway, I'm looking forward to your decision. Thank you!

**Comment by dragon3** [comment]
@jhump 
Thank you for the comment. I've just rebased this pull request. Please take a look when you get a chance.

**Review by jhump — APPROVED** [review]

**Comment by jhump** [comment]
@dragon3, can you address the lint issues? BTW, you can run the linter locally, before pushing commits to GitHub, by running `make lint`.

**Comment by dragon3** [comment]
@jhump 
Thank you for reviewing and merging 👍 

Could you create a new tag including this change?

**Comment by jhump** [comment]
> Could you create a new tag including this change?

@dragon3, I think we can do that later this week. I'm hoping to get one or more change (maybe two) merged before cutting the next release.

**Comment by dragon3** [comment]
@jhump 
Sorry for asking again, but could you create a new tag? 
Thank you!

**Comment by dragon3** [comment]
@jhump Thank you!

**Pull request merged**
